from otree.api import Bot, Submission
from . import *
import random

class PlayerBot(Bot):

    def play_round(self):
        # 1. INITIAL ROUND CONFIGURATIONS
        if self.round_number == 1:
            yield Consent
            yield Info, dict(
                age=random.randint(18, 70), 
                sex=random.choice(["M", "F"])
            )
            yield Instructions_no_player

        # 2. DECISION LOGIC: THE KNOW-WHAT (FIXED-HIERARCHY) PLAYER
        round_index = self.round_number - 1
        
        # Dynamically import the session variables generated by creating_session
        from . import matrices, color_1_list_1, color_2_list_1

        # Identify colors on the left and right for Player 1 (simulated Human role)
        color_left = matrices[round_index][color_1_list_1[round_index]]
        color_right = matrices[round_index][color_2_list_1[round_index]]

        # Trembling Hand Strategy (95% rational hierarchy, 5% random noise)
        if random.random() < 0.05:
            # Noise: Misclick or explore randomly
            choice = random.choice([1, 2])
        else:
            # Rational: Select the higher numerical color value
            if color_left > color_right:
                choice = 1
            else:
                choice = 2

        # Yield selection with a realistic human-like reaction time (in ms)
        yield Make_Choice, dict(
            response=choice, 
            answered_time=random.randint(380, 1150)
        )

        # NOTE: Show_Choice and WaitForBot have timeout_seconds defined, 
        # so oTree automatically bypasses them during automated tests.

        # 3. INTERACTIVE RESULTS PAGES
        # Player payoff is calculated during WaitForBot, so it's fully populated here
        if self.player.payoff == 1:
            yield Results_Correct
        else:
            # Red_Flash has a timeout, so it is bypassed automatically
            yield Results_Wrong

        # 4. TRIAL BREAKS
        if (self.round_number == Constants.num_rounds/3 or 
            self.round_number == 2*Constants.num_rounds/3):
            yield Break

        # 5. POST-GAME QUESTIONNAIRES & ENDPAGE
        if self.round_number == Constants.num_rounds:
            yield Final_Results
            yield Questions, dict(
                Q="I consistently chose whichever color seemed to have a higher value according to a fixed priority list."
            )
            yield Questions_1, dict(
                Q_1="Always stick to a strict hierarchy. Do not try to adapt to unexpected choices from your partner."
            )
            yield Thanks